services:
  - type: web
    name: fastapi-service
    env: python
    buildCommand: ""
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    plan: free
    envVars:
      - key: EVOLUTION_API_URL
        value: https://adella-noninteractive-torridly.ngrok-free.dev
      - key: EVOLUTION_API_KEY
        value: "ABD4739F7B4A-4936-A8DB-DF860D2EA53D"

  - type: web
    name: streamlit-dashboard
    env: python
    buildCommand: ""
    startCommand: "streamlit run app.py --server.port 10000 --server.address 0.0.0.0"
    plan: free
